__default__:
        partition: 'standard'
        group: 'bhurwitz'
        M: 'mattmiller899@email.arizona.edu'
        time: '48:00:00'
        nodes: '1'
        ntasks: '5'
        mem-per-cpu: '5gb'
        o: 'out/{rule}.{wildcards}.out'
        e: 'err/{rule}.{wildcards}.err'

